### PR TITLE
Removed additional Print statement

### PR DESCRIPTION
**Pull request by Utkarsh-Shukla12**
There was an additional print statement on line 16 on Explore the Data explore the section. Which have no purpose

### CODE REVIEW

**Comment by Utkarsh-Shukla12** [comment]
This my first contribution to any project!! Feels elated

**Comment by mnauf** [comment]
@Utkarsh-Shukla12  Congrats but they dont merge the pull requests :(

**Comment by Utkarsh-Shukla12** [comment]
@mnauf At least i did my part!!

**Comment by abhiojha8** [comment]
@mnauf We do now :)
@Utkarsh-Shukla12 Congrats!

**Pull request merged**
