### PR TITLE
Update filenames in project.py

### PR DESCRIPTION
**Pull request by rpalsaxena**
The autograder is giving an error `FileNotFoundError: [Errno 2] No such file or directory: 'Your_first_neural_network.ipynb'` due to mismatch of the file name. 

You can also check this knowledge answer: https://knowledge.udacity.com/questions/393933

### CODE REVIEW

**Review by DariaHem — APPROVED** [review]
# Thank you!

**Comment by DariaHem** [comment]
Is it okay right now? I tried to solve everything.

**Comment by rpalsaxena** [comment]
Hi @DariaHem ,

It seems the project.py file in the master branch is still not showing the changes.

**Comment by DariaHem** [comment]
Could you help me in solving that though? I uploaded today the file projects.py to show you that on master branch. Maybe this file is also somewhere where I do not see, the uploaded file looks like (so I changed the name): 

import argparse
import subprocess as sp
from udacity_pa import udacity
nanodegree = 'nd101'
projects = ['first_neural_network']
filenames = ['my_answers.py', 'Predicting_bike_sharing_data.ipynb']
def submit(args):
  # Do we prefer ipynb, html or both?
  # sp.call(['jupyter', 'nbconvert', '--to', 'html', 'dlnd_image_classification.ipynb'])
  udacity.submit(nanodegree, projects[0], filenames, 
                 environment = args.environment,
                 jwt_path = args.jwt_path)

**Comment by rpalsaxena** [comment]
I believe both of us don't have the write permission. The pull request can be updated only by the Udacity staff. 

@cezannec Could you please look into this as some students are facing issues due to this?

**Comment by DariaHem** [comment]
I changed the file as it was pointed by the other students on the forum. I have no idea what to do further, the project was calculated correctly using jupyter on udacity website, I uploaded it later to github to fill the requirements of the project 3.

**Pull request merged**
